from pathlib import Path

# PetTalk public browsing: avoid nullable viewer-id casts that can fail for guests.
p=Path('server_lib/community.js')
s=p.read_text(encoding='utf-8')
old='(p.is_public = true or (${viewerId}::text is not null and p.user_id = ${viewerId}))'
if s.count(old) < 3:
    raise SystemExit(f'community visibility pattern changed: {s.count(old)}')
s=s.replace(old, '(p.is_public = true or p.user_id = ${viewerId || ""})')
p.write_text(s,encoding='utf-8')

# PetNews: tolerate partial provider failures and keep query-scoped results visible.
p=Path('api/news.js')
s=p.read_text(encoding='utf-8')
old='async function fetchGoogleFallback(){const queries=["반려동물","반려견 OR 강아지","반려묘 OR 고양이","동물병원 OR 펫보험","유기동물 OR 동물보호"];const responses=await Promise.all(queries.map(async query=>{const url=`${GOOGLE_RSS}?q=${encodeURIComponent(query)}&hl=ko&gl=KR&ceid=KR:ko`;const response=await fetch(url,{headers:{"User-Agent":"PetGrow/1.0"}});if(!response.ok)throw new Error(`Google News RSS ${response.status}`);return parseGoogleRss(await response.text());}));return responses.flat();}'
new='async function fetchGoogleFallback(){const queries=["반려동물","반려견 OR 강아지","반려묘 OR 고양이","동물병원 OR 펫보험","유기동물 OR 동물보호"];const settled=await Promise.allSettled(queries.map(async query=>{const url=`${GOOGLE_RSS}?q=${encodeURIComponent(query)}&hl=ko&gl=KR&ceid=KR:ko`;const response=await fetch(url,{headers:{"User-Agent":"PetGrow/1.0"}});if(!response.ok)throw new Error(`Google News RSS ${response.status}`);return parseGoogleRss(await response.text());}));return settled.flatMap(r=>r.status==="fulfilled"?r.value:[]);}'
if old not in s: raise SystemExit('news fallback pattern changed')
s=s.replace(old,new)
old='async function prepare(raw){const normalized=dedupe(raw.filter(isPetRelevant).map(normalizeItem)).sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));const now=Date.now(),sevenDays=7*24*60*60*1000,recent=normalized.filter(item=>item.publishedAt&&now-new Date(item.publishedAt).getTime()<=sevenDays);const picked=(recent.length>=12?recent:normalized).slice(0,40);const enriched=await enrichArticleImages(picked);const byId=new Map(enriched.map(x=>[x.id,x]));return picked.map(x=>byId.get(x.id)||x);}'
new='async function prepare(raw){let normalized=dedupe(raw.filter(isPetRelevant).map(normalizeItem)).sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));if(!normalized.length)normalized=dedupe(raw.map(normalizeItem)).sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));const now=Date.now(),sevenDays=7*24*60*60*1000,recent=normalized.filter(item=>item.publishedAt&&now-new Date(item.publishedAt).getTime()<=sevenDays);const picked=(recent.length>=12?recent:normalized).slice(0,40);const enriched=await enrichArticleImages(picked);const byId=new Map(enriched.map(x=>[x.id,x]));return picked.map(x=>byId.get(x.id)||x);}'
if old not in s: raise SystemExit('news prepare pattern changed')
s=s.replace(old,new)
s=s.replace('return res.status(502).json({configured:true,items:[],error:"뉴스를 불러오지 못했어요. 잠시 후 다시 시도해 주세요."});','return res.status(200).json({configured:true,provider:"temporarily-unavailable",items:[],error:"뉴스를 불러오지 못했어요. 잠시 후 다시 시도해 주세요."});')
p.write_text(s,encoding='utf-8')

# Map: one stable viewport after each search; remove competing fitBounds/zoom operations.
p=Path('src/App.jsx')
s=p.read_text(encoding='utf-8')
old='const map=new K.Map(mapRef.current,{center:centerPos,level:4});mapObj.current=map;mapObj.current.__engine="kakao";\n          window.setTimeout(()=>{try{map.relayout();map.setCenter(centerPos)}catch{}},60);\n          window.setTimeout(()=>{try{map.relayout()}catch{}},260);'
new='const map=new K.Map(mapRef.current,{center:centerPos,level:5});mapObj.current=map;mapObj.current.__engine="kakao";\n          window.setTimeout(()=>{try{map.relayout();map.setCenter(centerPos);map.setLevel(5)}catch{}},80);'
if old not in s: raise SystemExit('kakao map init pattern changed')
s=s.replace(old,new,1)
old='if(places.length){if(places.length===1){map.setCenter(new K.LatLng(places[0].lat,places[0].lng));map.setLevel(3);}else{map.setBounds(bounds,40,40,40,40);}}\n          window.setTimeout(()=>map.relayout?.(),60);'
new='if(places.length){map.setCenter(centerPos);map.setLevel(5);}\n          window.setTimeout(()=>{try{map.relayout?.();map.setCenter(centerPos);map.setLevel(5)}catch{}},80);'
if old not in s: raise SystemExit('kakao map bounds pattern changed')
s=s.replace(old,new,1)
old='if(places.length){if(places.length===1){map.setView([places[0].lat,places[0].lng],16);}else{const close=places.filter(p=>Number(p.distance)<=1000);if(close.length){const b2=L.latLngBounds([[center.lat,center.lng]]);close.slice(0,12).forEach(p=>b2.extend([p.lat,p.lng]));map.fitBounds(b2.pad(.16),{maxZoom:16,padding:[28,28]});}else{map.setView([center.lat,center.lng],14);}}}\n    window.setTimeout(()=>map.invalidateSize(),60);\n    window.setTimeout(()=>map.invalidateSize(),260);'
new='map.setView(c,14,{animate:false});\n    window.setTimeout(()=>{try{map.invalidateSize({pan:false});map.setView(c,14,{animate:false})}catch{}},80);'
if old not in s: raise SystemExit('leaflet map bounds pattern changed')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# Cohesive premium responsive design across Home/About/functional pages/MyPage/Saju/Tarot/PetTalk/News/Nearby.
p=Path('src/petgrow-premium-20260817.css')
css=p.read_text(encoding='utf-8')
marker='/* PETGROW_FULL_FIX_REDESIGN_20260817 */'
if marker in css: css=css.split(marker)[0].rstrip()+"\n"
css += '''

/* PETGROW_FULL_FIX_REDESIGN_20260817 */
:root{--pg-bg:#f6f4ee;--pg-surface:#fff;--pg-soft:#f0f5ef;--pg-warm:#fbf7ee;--pg-rose:#fbf1ef;--pg-blue:#eef5f6;--pg-text:#243129;--pg-sub:#68736c;--pg-line:#e1e6df;--pg-primary:#315f40;--pg-primary-soft:#eaf3ec;--pg-radius:22px;--pg-shadow:0 10px 30px rgba(38,58,45,.065)}
html,body,#root{min-height:100%;background:var(--pg-bg)!important;color:var(--pg-text)!important}body{font-size:15px;line-height:1.65;letter-spacing:-.012em}
.petgrow-content-stage{width:100%;max-width:1180px;margin:0 auto;padding:28px 24px 72px!important;box-sizing:border-box}.petgrow-content-stage>*,.legal-page-shell,.feature-page-shell,.nearby-page,.petnews-v10,.community-page{box-sizing:border-box}
.petgrow-unified-hero{margin:0 auto 24px!important;max-width:1040px!important;border:1px solid var(--pg-line)!important;border-radius:30px!important;background:linear-gradient(135deg,#fffdf9 0%,#f0f6ef 65%,#eef6f4 100%)!important;box-shadow:var(--pg-shadow)!important;padding:32px 34px!important}.petgrow-unified-hero h1,.petgrow-unified-hero h2{font-weight:800!important;letter-spacing:-.04em!important}.petgrow-unified-hero p{color:var(--pg-sub)!important;font-size:14px!important;line-height:1.75!important}
.home-page,.home-wrap,.home-container,.landing-page{max-width:1100px!important;margin-left:auto!important;margin-right:auto!important}.landing-section{padding:54px 0!important}.landing-wrap{max-width:1040px!important;margin:0 auto!important;padding:0 22px!important}.landing-section-title{font-size:clamp(27px,3.2vw,42px)!important;line-height:1.16!important;font-weight:800!important;letter-spacing:-.045em!important;color:var(--pg-text)!important}.landing-community-wrap,.landing-fun-grid{gap:24px!important}.landing-cta{min-height:46px!important;border-radius:15px!important;font-weight:700!important}
.home-service-card,.landing-feature-card,.landing-card,.landing-mini-teaser-item{border:1px solid var(--pg-line)!important;border-radius:22px!important;box-shadow:var(--pg-shadow)!important;transition:transform .16s ease,box-shadow .16s ease!important}.home-service-card:hover,.landing-feature-card:hover,.landing-card:hover{transform:translateY(-2px)!important;box-shadow:0 15px 38px rgba(38,58,45,.09)!important}
.legal-page-shell,.feature-page-shell,.feature-module-shell,.community-page,.pettalk-safe-fallback,.petnews-v10,.music-page,.petmusic-page,.nearby-page{max-width:940px!important;margin-left:auto!important;margin-right:auto!important}.feature-page-shell,.feature-module-shell{background:transparent!important}.feature-page-shell .bg-card,.feature-module-shell .bg-card,.feature-page-shell .card,.feature-module-shell .card,.community-page .bg-card,.petnews-v10 .bg-card,.nearby-page .bg-card{border:1px solid var(--pg-line)!important;border-radius:22px!important;background:#fff!important;box-shadow:var(--pg-shadow)!important}.feature-page-shell h1,.feature-page-shell h2,.feature-module-shell h1,.feature-module-shell h2{font-weight:800!important;letter-spacing:-.04em!important;color:var(--pg-text)!important}.feature-page-shell p,.feature-module-shell p{color:var(--pg-sub)}.feature-page-shell .bg-btn,.feature-module-shell .bg-btn{border-radius:14px!important;min-height:44px!important;font-size:14px!important;font-weight:700!important}
.feature-page-saju,.feature-page-tarot,.saju-page,.tarot-page{max-width:900px!important;margin:0 auto!important}.feature-page-saju .feature-module-shell,.feature-page-tarot .feature-module-shell,.saju-page .feature-module-shell,.tarot-page .feature-module-shell{padding:4px 0 26px!important}.feature-page-saju .bg-card,.feature-page-tarot .bg-card,.saju-page .bg-card,.tarot-page .bg-card{border-radius:22px!important;border-color:var(--pg-line)!important;box-shadow:var(--pg-shadow)!important}.feature-page-saju button,.feature-page-tarot button,.saju-page button,.tarot-page button{font-family:inherit!important}.tarot-grid,.tarot-card-grid,.tarot-deck,.tarot-cards{gap:10px!important}.tarot-grid button,.tarot-card-grid button,.tarot-deck button,.tarot-cards button{border-radius:16px!important}
.pettalk-safe-fallback,.community-page{min-height:460px!important}.cm-search-actions,.cm-toolbar,.community-toolbar{background:#fff!important;border:1px solid var(--pg-line)!important;border-radius:18px!important;box-shadow:var(--pg-shadow)!important}.cm-post-card,.community-card,.community-list>*{background:#fff!important;border:1px solid var(--pg-line)!important;border-radius:20px!important;box-shadow:0 5px 18px rgba(38,58,45,.045)!important}.cm-post-card button,.community-page button{font-family:inherit!important}
.petnews-v10,.petnews-page{min-height:460px!important}.petnews-list,.petnews-grid{display:grid!important;gap:14px!important}.petnews-card,.petnews-card-v10{background:#fff!important;border:1px solid var(--pg-line)!important;border-radius:22px!important;overflow:hidden!important;box-shadow:var(--pg-shadow)!important}.petnews-card-media,.petnews-image-fallback,.petnews-card-v10>img{aspect-ratio:16/9!important;background:linear-gradient(135deg,#edf5ee,#f8f4ea)!important;overflow:hidden!important}.petnews-card-media img,.petnews-card-v10 img,.news-card img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}.petnews-title{color:var(--pg-text)!important;font-weight:800!important}.petnews-summary{color:var(--pg-sub)!important}
.my-page-head{padding:26px 28px!important;border:1px solid var(--pg-line)!important;border-radius:24px!important;background:linear-gradient(135deg,#fffdf9,#eef5ef)!important;box-shadow:var(--pg-shadow)!important;margin-bottom:18px!important}.my-menu-grid{gap:12px!important}.my-menu-card{border:1px solid var(--pg-line)!important;border-radius:20px!important;box-shadow:var(--pg-shadow)!important;color:var(--pg-text)!important}.my-menu-pink{background:var(--pg-rose)!important}.my-menu-blue{background:var(--pg-blue)!important}.my-menu-purple{background:#f4eff8!important}.my-menu-mint{background:var(--pg-primary-soft)!important}.my-activity-stack{display:grid!important;gap:12px!important}.my-activity-stack>.my-menu-card:nth-of-type(1),.my-activity-stack>button:nth-of-type(1){background:#f4eff8!important}.my-activity-stack>.my-menu-card:nth-of-type(2),.my-activity-stack>button:nth-of-type(2){background:var(--pg-rose)!important}.my-activity-stack>.my-menu-card:nth-of-type(3),.my-activity-stack>button:nth-of-type(3){background:var(--pg-primary-soft)!important}.my-activity-stack>.my-menu-card,.my-activity-stack>button{border:1px solid var(--pg-line)!important;border-radius:20px!important;box-shadow:var(--pg-shadow)!important}
.nearby-map-card{overflow:hidden!important;border-radius:22px!important;border:1px solid var(--pg-line)!important;background:#fff!important;box-shadow:var(--pg-shadow)!important}.nearby-map,.nearby-map .leaflet-container{height:440px!important;min-height:440px!important;max-height:440px!important;width:100%!important;transition:none!important;animation:none!important}.nearby-place-card,.nearby-result-card{border-radius:18px!important;border:1px solid var(--pg-line)!important;background:#fff!important}
.desktop-nav button,.sidebar-nav button,.ham-nav-item,.mobile-bottom-nav button{font-weight:600!important;letter-spacing:-.02em!important}button,.bg-btn,.btn{font-family:inherit!important}.bg-input,input,select,textarea{font-family:inherit!important;border-radius:14px!important}
@media(max-width:1024px){.petgrow-content-stage{padding:24px 20px 64px!important}.petgrow-unified-hero{border-radius:26px!important;padding:28px!important}.landing-section{padding:44px 0!important}.nearby-map,.nearby-map .leaflet-container{height:400px!important;min-height:400px!important;max-height:400px!important}}
@media(max-width:760px){body{font-size:14px!important}.petgrow-content-stage{padding:16px 14px 76px!important}.petgrow-unified-hero{padding:21px 19px!important;border-radius:21px!important;margin-bottom:16px!important}.petgrow-unified-hero h1,.petgrow-unified-hero h2{font-size:25px!important}.landing-section{padding:34px 0!important}.landing-wrap{padding:0 14px!important}.landing-section-title{font-size:27px!important}.home-service-card,.landing-feature-card,.landing-card{border-radius:18px!important}.feature-page-shell,.feature-module-shell,.legal-page-shell,.community-page,.petnews-v10,.nearby-page{width:100%!important;max-width:100%!important;padding-left:0!important;padding-right:0!important}.feature-page-shell h1,.feature-module-shell h1{font-size:27px!important}.feature-page-shell h2,.feature-module-shell h2{font-size:22px!important}.my-page-head{padding:20px!important;border-radius:20px!important}.my-menu-grid{grid-template-columns:1fr!important}.my-menu-card{min-height:0!important;border-radius:18px!important}.petnews-card,.petnews-card-v10{grid-template-columns:1fr!important}.petnews-card-media{min-height:0!important;height:auto!important;aspect-ratio:16/9!important}.petnews-card-body{padding:16px!important}.nearby-map,.nearby-map .leaflet-container{height:360px!important;min-height:360px!important;max-height:360px!important}.tarot-grid,.tarot-card-grid,.tarot-deck,.tarot-cards{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:7px!important}input,select,textarea{font-size:16px!important}}
@media(max-width:390px){.petgrow-content-stage{padding-left:12px!important;padding-right:12px!important}.petgrow-unified-hero h1,.petgrow-unified-hero h2{font-size:23px!important}.nearby-map,.nearby-map .leaflet-container{height:330px!important;min-height:330px!important;max-height:330px!important}.my-menu-card{padding:15px!important}.tarot-grid,.tarot-card-grid,.tarot-deck,.tarot-cards{gap:5px!important}}
'''
p.write_text(css,encoding='utf-8')
